[package]
name = "api_axum"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "api_axum"

[dependencies]
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
num_cpus = "*"
axum = "0.7"
